package artifacts

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/herdiagusthio/cbmem/internal/storage"
)

func WriteRoutesMD(ctx context.Context, outputDir, repo string, store *storage.Store) error {
	syms, err := store.ListSymbols(ctx, repo, 0)
	if err != nil {
		return err
	}
	var rows []string
	for _, s := range syms {
		if s.Language == "yaml" || s.Language == "dockerfile" || s.Language == "proto" || s.Language == "sql" {
			continue
		}
		sig := strings.ToLower(s.Signature)
		qual := strings.ToLower(s.QualifiedName)
		file := strings.ToLower(s.FilePath)
		isRoute := strings.Contains(file, "handler") || strings.Contains(file, "route") || strings.Contains(file, "controller") ||
			strings.Contains(qual, "handler") || strings.Contains(qual, "route") ||
			strings.Contains(sig, "echo.context") || strings.Contains(sig, "gin.context") ||
			strings.Contains(sig, "http.request") || strings.Contains(sig, "fiber.ctx")
		if !isRoute {
			continue
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | %s:%d | `%s` |", s.QualifiedName, s.SymbolKind, s.FilePath, s.StartLine, truncate(s.Signature, 80)))
	}
	var b strings.Builder
	b.WriteString("# Routes — " + repo + "\n\n")
	if len(rows) == 0 {
		b.WriteString("_No handler/route symbols detected (heuristic: handler/route file or echo/gin/http signature)._ \n")
	} else {
		b.WriteString(fmt.Sprintf("_%d routes/handlers detected._\n\n", len(rows)))
		b.WriteString("| Symbol | Kind | Location | Signature |\n|---|---|---|---|\n")
		for _, r := range rows {
			b.WriteString(r + "\n")
		}
	}
	b.WriteString("\n> Generated by `cbmem index`. Heuristic; add `// cbmem:route GET /path` comments for explicit routes (ponytail).\n")
	return os.WriteFile(filepath.Join(outputDir, "routes.md"), []byte(b.String()), 0644)
}

func WriteCallgraphDOT(ctx context.Context, outputDir, repo string, store *storage.Store) error {
	syms, err := store.ListSymbols(ctx, repo, 0)
	if err != nil {
		return err
	}
	edges, err := store.ListEdges(ctx, repo)
	if err != nil {
		return err
	}
	// map qualified -> id for node names
	idByQual := make(map[string]bool, len(syms))
	for _, s := range syms {
		idByQual[s.QualifiedName] = true
	}
	var b strings.Builder
	b.WriteString("digraph " + sanitize(repo) + " {\n")
	b.WriteString("  rankdir=LR;\n  node [shape=box, fontsize=10];\n")
	if len(syms) > 200 {
		b.WriteString(fmt.Sprintf("  // %d symbols, %d edges — truncated graph (first 200 nodes)\n", len(syms), len(edges)))
		syms = syms[:200]
	}
	for _, s := range syms {
		label := s.QualifiedName
		if len(label) > 40 {
			label = label[:40] + "…"
		}
		b.WriteString(fmt.Sprintf("  %q [label=%q];\n", s.QualifiedName, label))
	}
	limit := 500
	for i, e := range edges {
		if i >= limit {
			b.WriteString(fmt.Sprintf("  // ... %d more edges truncated\n", len(edges)-limit))
			break
		}
		b.WriteString(fmt.Sprintf("  %q -> %q;\n", e.SrcQualified, e.DstQualified))
	}
	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(outputDir, "callgraph.dot"), []byte(b.String()), 0644)
}

func sanitize(s string) string {
	r := strings.ReplaceAll(s, "-", "_")
	r = strings.ReplaceAll(r, ".", "_")
	r = strings.ReplaceAll(r, "/", "_")
	return r
}

func truncate(s string, n int) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}
