package artifacts

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/herdiagusthio/cbmem/internal/linker"
	"github.com/herdiagusthio/cbmem/internal/storage"
)

func WriteNotesMD(ctx context.Context, outputDir, repo string, store *storage.Store) error {
	stale, _ := linker.StaleCheck(ctx, outputDir, store, repo)
	// also count total links
	total := 0
	if data, err := os.ReadFile(filepath.Join(outputDir, "links.jsonl")); err == nil {
		for _, b := range data {
			if b == '\n' {
				total++
			}
		}
		if len(data) > 0 && data[len(data)-1] != '\n' {
			total++
		}
	}
	var out string
	out += "# Notes — " + repo + "\n\n"
	out += fmt.Sprintf("_%d links, %d stale._\n\n", total, len(stale))
	if len(stale) == 0 {
		out += "No stale links. Run `cbmem links [repo]` to refresh `links.jsonl`, then `cbmem stale`.\n"
	} else {
		out += "## Stale\n\n| Symbol | Target | Kind |\n|---|---|---|\n"
		for _, s := range stale {
			out += fmt.Sprintf("| `%s` | `%s` | %s |\n", s.Symbol, s.TargetPath, s.LinkKind)
		}
		out += "\n> Stale = hash drift or deleted symbol since `links.jsonl` was written.\n"
	}
	out += "\n> Generated by `cbmem`. ponytail: per-symbol `<!-- cbmem:symbol=... -->` annotations when notes.md matures.\n"
	return os.WriteFile(filepath.Join(outputDir, "notes.md"), []byte(out), 0644)
}
